print("Hello")
print("This line was added later in the process!")
your_name = input("What is your name: ")
print("Hi " + your_name.capitalize())
print("Your name is " + str(len(your_name)) + " characters long.")